use_frameworks!

target 'IPAddressKeyboard_Example' do
  pod 'IPAddressKeyboard', :path => '../'

  target 'IPAddressKeyboard_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
